package com.taskmanagementg7.TaskManager.mapper;

import com.taskmanagementg7.TaskManager.dtos.TaskDTO;
import com.taskmanagementg7.TaskManager.entity.Task;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface TaskMapper {

    // MapStruct will automatically use this method to handle List<Task> to List<TaskDTO> conversion.
    List<TaskDTO> toDtoList(List<Task> tasks);

    @Mapping(target = "assignments", ignore = true)

    // Ignore DTO fields that must be manually populated in the controller
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "userName", ignore = true)
    TaskDTO toDto(Task task);

    // Use this for POST/PUT requests (mapping DTO back to Entity)
    @Mapping(target = "taskId", ignore = true)        // ID is generated by DB
    @Mapping(target = "assignments", ignore = true)   // Assignments must be managed by service/controller
    Task toEntity(TaskDTO taskDTO);
}
